#!/bin/sh
#postinstall

olsrd2dir="/config/olsrd2/"
log="/var/log/0xffolsrd2.log"
configfile="olsrd2.conf"

# add google v6 dns on plain install
if [ ! -f $olsrd2dir$configfile ] && [ ! -f $olsrd2dir"olsrd2" ] && [ ! -f /config/scripts/post-config.d/startolsrd2.sh ]; then
    if [ $(grep -E "^    name-server 2001:4860:4860::8888" /config/config.boot | wc -l) == "0" ]; then
        docommands="1"
        executecmd1="set system name-server '2001:4860:4860::8888'"
    fi
    if [ $(grep -E "^    name-server 2001:4860:4860::8844" /config/config.boot | wc -l) == "0" ]; then
        docommands="1"
        executecmd2="set system name-server '2001:4860:4860::8844'"
    fi
    if [ "$docommands" ]; then
        echo "Adding Google v6-DNS servers to setup..." >>$log
cmd="/opt/vyatta/sbin/vyatta-cfg-cmd-wrapper"
tfile=$(mktemp)
(
$cmd begin
ret=0
if [ $ret == 0 ] && [ "$executecmd1" ]; then
    $cmd $executecmd1 || ret=1
fi
if [ $ret == 0 ] && [ "$executecmd2" ]; then
    $cmd $executecmd2 || ret=1
fi
if [ $ret == 0 ]; then
    $cmd commit || ret=1
fi
if [ $ret == 0 ]; then
    $cmd save || ret=1
fi
$cmd end
exit $ret
) >$tfile 2>&1
ret=$?
output=$(cat $tfile)
rm -f $tfile
echo $output >> $log

    fi
fi

#enable autostart - only on "plain install" and olsr-v1/v6 is not running
olsr1v6running=$(ps aux | grep -E "olsrd6|olsrdv6" | grep -v grep | wc -l)
chmod 755 $olsrd2dir""startolsrd2.sh
if [ ! -f $olsrd2dir$configfile ] && [ "$olsr1v6running" == "0" ]; then
    cp $olsrd2dir""startolsrd2.sh /config/scripts/post-config.d/startolsrd2.sh >>$log 2>>$log
fi

# establish default configfile if config not already there
if [ ! -f $olsrd2dir$configfile ] && [ -f $olsrd2dir"olsrd2_default.conf" ]; then
    cp $olsrd2dir"olsrd2_default.conf" $olsrd2dir$configfile >>$log 2>>$log
fi

#check for olsrd2 version
if [ ! -f $olsrd2dir"olsrd2" ]; then
    #there is no previous olsrd2
    cp $olsrd2dir"olsrd2_inst" $olsrd2dir"olsrd2" >>$log 2>>$log
    chmod 755 $olsrd2dir""olsrd2 >>$log 2>>$log
elif [ $(sha1sum $olsrd2dir""olsrd2 | awk {'print $1'}) != $(sha1sum $olsrd2dir""olsrd2_inst | awk {'print $1'}) ]; then
    #package contains new/changed olsrd2 binary
    cp $olsrd2dir"olsrd2_inst" $olsrd2dir"olsrd2"  >>$log 2>>$log
    chmod 755 $olsrd2dir""olsrd2  >>$log 2>>$log
    #restart daemon!
    #stop running daemon
    ps aux | grep '$olsrd2dir""olsrd2 -l $olsrd2dir"olsrd2.conf"' | grep -v grep | awk '{print $2;}' | xargs kill >>$log 2>>$log
    sleep 1
    rm -f /var/lock/olsrd2 >>$log 2>>/dev/null
fi

rm -f $olsrd2dir"olsrd2_inst" >>$log 2>>$log

# start olsrd2, only if enabled and an v6-address is assigned somewhere
if [ $(ip -6 addr show lo | grep global | wc -l) != "0" ] && [ -f /config/scripts/post-config.d/startolsrd2.sh ]; then
    #fire up olsrd2 daemon
    $olsrd2dir""olsrd2 -l $olsrd2dir"olsrd2.conf" >>$log 2>>$log
fi

exit 0
