#!/bin/sh
#postinstall

olsrd2dir="/config/olsrd2/"
log="/var/log/0xffolsrd2.log"

#enable autostart
chmod 755 $olsrd2dir""startolsrd2.sh
cp $olsrd2dir""startolsrd2.sh /config/scripts/post-config.d/startolsrd2.sh >>$log 2>>$log

# establish default config file if config not already there
file="olsrd2.conf"
if [ ! -f $olsrd2dir$file ] && [ -f $olsrd2dir"olsrd2_default.conf" ]; then
    cp $olsrd2dir"olsrd2_default.conf" $olsrd2dir$file >>$log 2>>$log
fi

#check for olsrd2 version
if [ ! -f $olsrd2dir"olsrd2" ]; then
    #there is no previous olsrd2
    cp $olsrd2dir"olsrd2_inst" $olsrd2dir"olsrd2" >>$log 2>>$log
    chmod 755 $olsrd2dir""olsrd2 >>$log 2>>$log
    #fire up olsrd2 daemon
    $olsrd2dir""olsrd2 -l $olsrd2dir"olsrd2.conf" >>$log 2>>$log
elif [ $(sha1sum olsrd2 | awk {'print $1'}) != $(sha1sum olsrd2_inst | awk {'print $1'}) ]; then
    #package contains new/changed olsrd2 binary
    cp $olsrd2dir"olsrd2_inst" $olsrd2dir"olsrd2"  >>$log 2>>$log
    chmod 755 $olsrd2dir""olsrd2  >>$log 2>>$log
    #restart daemon!
    #stop running daemon
    ps aux | grep $olsrd2dir""olsrd2 -l $olsrd2dir"olsrd2.conf" | grep -v grep | awk '{print $2;}' | xargs kill >>$log 2>>$log
    sleep 1
    rm -f /var/lock/olsrd2 >>$log 2>>$log
    #fire up olsrd2 daemon
    $olsrd2dir""olsrd2 -l $olsrd2dir"olsrd2.conf" >>$log 2>>$log    
fi

rm -f $olsrd2dir"olsrd2_inst" >>$log 2>>$log

exit 0
